name: WordPress Plugin Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  plugin-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run WordPress Plugin Check
        uses: WordPress/plugin-check-action@v1.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          slug: woo-sku-barcode

