name: 'WordPress Plugin Check'

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - 'releases/*'

jobs:
  plugin-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Exclude hidden files
        run: |
          find . -type f -name ".*" -exec rm -f {} \;

      - name: Run WordPress Plugin Check
        uses: WordPress/plugin-check-action@v1.1.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          slug: woo-sku-barcode

